import link1 from "../asset/carousel1.jpeg";
export const SliderData = [
    {
        id: 1,
        title: 'The Assembly NFT',
        price: '1.5',
        blockchain: 'SOL',
        website: "https://www.theassembly.gg",
        category: 'An Nft Card Game that brings together ancient wariors',
        linking: 'https://vhagln2icqas2l4j6nvbazmdbv5xd3wfp3x4ikbkgaqvzp5ebysa.arweave.net/qcBlt0gUAS0vifNqEGWDDXtx7sV-78QoKjAhXL-kDiQ',
    },
    {
        id: 2,
        title: 'That little girl was me nft',
        price: '.45',
        blockchain: 'ETH',
        content: 'This is an NFT for Women and those who support them on the ETh lockchain, commisioned by Good Trubble',
        website: "https://www.thatlittlegirlwasmenft.com",
        category: 'This collection was built on the ethereum blockchain and was commisioned',
        linking: "https://477ua2acxfpkngoxrc4cyupgwzbrffae6chsna3qtnwioygokqsa.arweave.net/5_9AaAK5XqaZ14i4LFHmtkMSlATwjyaDcJtsh2DOVCQ",
    },
    {
        id: 3,
        title: 'The Black Jesus Project',
        price: '.5',
        blockchain: 'SOL',
        content: 'this project is on the sol',
        website: "https://www.blackjesusproject.io",
        category: 'Black Jeusus Project, is a NFT project built for Outhouse Ministries',
        linking: "https://xoocyeehkw6e6jlhqonng4ls4ffsblrymke6uzrefpfyafy7gwnq.arweave.net/u5wsEIdVvE8lZ4Oa03Fy4UsgrjhiiepmJCvLgBcfNZs",
    },
    {
        id: 4,
        title: 'FreshKingz',
        price: '1.5',
        blockchain: 'SOL',
        website: "https://zeallionairez.com/",
        category: 'Freshkingz is an platform for artists and creators to display their work',
        linking: 'https://666dmtjhpy4pipb235k3vfzmbup6ufcowmuazdrtjez23zbjo7tq.arweave.net/97w2TSd-OPQ8Ot9VupcsDR_qFE6zKAyOM0kzreQpd-c',
    },
    {
        id: 5,
        title: 'Dead Mans Hand',
        price: '0.15',
        blockchain: 'SOL',
        content: 'This is a card game built, with the intent to sustain a training program',
        website: "https://mint.texaglo.com",
        category: 'This is a card game built, with the intent to sustain a training program',
        linking: "https://edzg4zgykmrazs5mpkrt42tiqpgzm42jw3iqk2pcitslnjth5caa.arweave.net/IPJuZNhTIgzLrHqjPmpog82Wc0m20QVp4kTktqZn6IA",
    },
    {
        id: 6,
        title: 'Dragons Origin',
        price: '4.5',
        blockchain: 'SOL',
        website: "https://dragonsoriginsnft.com/",
        category: 'Dragons have arrived on the blockchain and are here come check it out',
        linking: 'https://2ycj4lof24gtr225vj4kdczcip3w5zx5ks7myqsrbm5ipje7ukta.arweave.net/1gSeLcXXDTjrXap4oYsiQ_du5v1UvsxCUQs6h6SfoqY',
    }/*,
    {
        id: 7,
        title: 'KeyBooks',
        price: '0.45',
        blockchain: 'SOL',
        content: '',
        website: "https://main.d3ei5spmpesspt.amplifyapp.com",
        category: 'This is a card built to facilitate in person events',
        linking: "https://gateway.pinata.cloud/ipfs/QmcoRYPZmy68NnZbJMmBnLWqegVg585VTBnMeXKHihQ2Dz",
    }*/
    
]